name: PlayerGrowth
version: '${version}'
main: org.misqzy.playerGrowth.PlayerGrowth
author: MISQZY
api-version: '1.20.5'
softdepend: [PlaceholderAPI]
commands:
  height:
    description: Show your current growth
    usage: /height
  playergrowth:
    description: Main admin command for PlayerGrowth
    usage: /playergrowth reload
    aliases: [pg]
    permission: playergrowth.reload
  growthtime:
    description: Show time until growth end
    usage: /growthtime
  setheight:
    description: Set custom height for a player
    usage: /setheight [player] <height|remove>
    permission: playergrowth.setheight
permissions:
  height:
    description: Show player height
    default: true
  playergrowth.reload:
    description: Allows reloading the plugin config and messages
    default: op
  playergrowth.setheight:
    description: Allows setting custom player height
    default: op
